[package]
name = "rocket-streaming-1"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "=0.5.0-rc.3"
tokio = {version = "1.30.0", features = ["full"]}
tokio-util = { version = "0.7", features = ["io"] }
multer = "2.0"
infer = "0.3"